# Generated by Django 6.0.1 on 2026-01-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalbooking',
            name='day',
        ),
        migrations.RemoveField(
            model_name='internalbooking',
            name='slot',
        ),
    ]
