# Generated by Django 6.0.1 on 2026-01-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_internalbooking_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalbooking',
            name='slot',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalbooking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internalbooking',
            name='reg_no',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
    ]
